---
- name: Install initial packages
  hosts: localhost
  connection: local
  become: yes

  tasks:
   - name: Kubernetes (kubectl)
      shell: |
        curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
        echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
        sudo apt-get update
        sudo apt-get install -y kubectl
    
    - name: Kubernetes (microk8s)
      snap:
        name:
          - microk8s
        classic: yes

    - name: Helm
      shell: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh
        rm get_helm.sh
      args:
        chdir: /tmp/


